name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Only deploy when index.html is changed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Use latest version to avoid deprecated warning

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Specify Node.js version 20

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

    - name: Deploy to GitHub Pages
      run: |
        git remote set-url origin https://github.com/Ylli831/GH-Deployment-Workflow
        git add -A
        git commit -m "Deploy updates"
        git push origin main:gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

