name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Only deploy when index.html is changed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to GitHub Pages
      run: |
        # Create and switch to gh-pages branch if it doesn't exist
        git checkout -b gh-pages || git checkout gh-pages
        
        # Ensure we have the latest changes
        git merge main
        
        # Push to gh-pages branch
        git push -f origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
