name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Only deploy when index.html is changed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@github.com"

    - name: Check for changes to deploy
      run: |
        git diff --exit-code || echo "Changes detected, ready to deploy"
      continue-on-error: true

    - name: Deploy to GitHub Pages
      run: |
        git remote set-url origin https://github.com/Ylli831/GH-Deployment-Workflow.git
        git add -A
        git diff --exit-code || git commit -m "Deploy updates"
        git push origin main:gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB

