name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Only trigger when the index.html file is changed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (for static site generator, if needed)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build the site (if using a static site generator like Jekyll, Hugo, etc.)
        run: |
          # For example, if using Jekyll, you would run 'bundle exec jekyll build'
          # But for now, since it's just an index.html, we can skip this
          echo "No build step required"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up
        run: rm -rf ./*

