name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - 'index.html'  # Only deploy when index.html is changed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write      # Add this permission
      id-token: write   # Add this permission
    
    # Add this environment configuration
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to GitHub Pages
      run: |
        git checkout -b gh-pages || git checkout gh-pages
        git merge main
        git push -f origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      id: deployment  # Add this ID to reference in the environment url
      uses: actions/deploy-pages@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
